export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};


export const ERROR_MESSAGES = {
  UNAUTHORIZED_ACCESS: 'Unauthorized access. Please log in.',
  LEAD_NOT_FOUND: 'Lead not found.',
  CONTACT_NOT_FOUND: 'Contact not found.',
  ACCOUNT_NOT_FOUND: 'Account not found.',
  DEAL_NOT_FOUND: 'Deal not found.',
  TASK_NOT_FOUND: 'Task not found.',
  NOTE_NOT_FOUND: 'Note not found.',
  EMAIL_FAILED: 'Failed to send email. Please try again later.',
  INVALID_STATUS: 'Invalid status provided.',
  UNAUTHORIZED_USER: 'Unauthorized user.',
  ACCESS_DENIED: 'Access denied. You do not have the necessary permissions.',
  SERVER_ERROR: 'An unexpected server error occurred.',
  VALIDATION_ERROR: 'Input validation failed.',
  TOKEN_EXPIRED: 'Session has expired. Please log in again.',
  INVALID_TOKEN: 'Invalid token.',
  USER_NOT_FOUND: 'User not found.',
  LOGIN_FAILED: 'Incorrect email or password.',
  PASSWORD_REQUIRED: 'Password is required.',
  EMAIL_EXISTS: 'This email is already associated with an account.',
  EMAIL_NOT_FOUND: 'No account found with this email.',
  REGISTRATION_FAILED: 'Failed to register user.',
  ACTION_FAILED: 'Action could not be completed.',
  MISSING_FIELDS: 'Required fields are missing.',
  DUPLICATE_ENTRY: 'This record already exists.',
  OPERATION_NOT_ALLOWED: 'This operation is not allowed.',
  RESOURCE_LOCKED: 'This resource is currently locked or being modified.',
  TOO_MANY_REQUESTS: 'Too many requests. Please try again later.',
  INVALID_INPUT: 'Invalid input provided.',
  ROUTE_NOT_FOUND: 'API route not found.',
};


export const SUCCESS_MESSAGES = {
  LEAD_CREATED: 'Lead has been successfully created.',
  LEAD_UPDATED: 'Lead details updated successfully.',
  LEAD_DELETED: 'Lead has been deleted successfully.',
  CONTACT_ADDED: 'Contact has been added successfully.',
  CONTACT_UPDATED: 'Contact updated successfully.',
  CONTACT_DELETED: 'Contact removed successfully.',
  ACCOUNT_CREATED: 'Account created successfully.',
  ACCOUNT_UPDATED: 'Account updated successfully.',
  DEAL_CREATED: 'Deal has been created.',
  DEAL_UPDATED: 'Deal updated successfully.',
  DEAL_WON: 'Deal marked as won.',
  DEAL_LOST: 'Deal marked as lost.',
  TASK_COMPLETED: 'Task marked as completed.',
  TASK_CREATED: 'Task has been created successfully.',
  NOTE_ADDED: 'Note added to the record successfully.',
  EMAIL_SENT: 'Email sent successfully.',
  LOGIN_SUCCESS: "You're signed in.",
  LOGOUT_SUCCESS: "You've been logged out.",
  PASSWORD_RESET_SUCCESS: "Password has been reset successfully.",
  USER_CREATED: 'User account created successfully.',
  USER_UPDATED: 'User profile updated successfully.',
  DATA_RETRIEVED: 'Data retrieved successfully.',
  ACTION_SUCCESS: 'Action completed successfully.',
  OPERATION_SUCCESS: 'Operation completed successfully.',
  REFRESH_TOKEN_SUCCESS: "Session refreshed.",
};
